#!/usr/bin/env bash
# DockPilot installer — macOS and Linux
# Usage: bash install.sh
set -euo pipefail

REPO_URL="https://github.com/yourusername/dockpilot.git"
INSTALL_DIR="$HOME/.local/share/dockpilot"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/dockpilot"
DESKTOP_FILE="$HOME/.local/share/applications/dockpilot.desktop"
ICON_SRC="$INSTALL_DIR/assets/icon.png"

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[dockpilot]${NC} $*"; }
warn()  { echo -e "${YELLOW}[dockpilot]${NC} $*"; }
error() { echo -e "${RED}[dockpilot] ERROR:${NC} $*" >&2; exit 1; }

# ── Platform detection ────────────────────────────────────────────────────────
case "$(uname -s)" in
  Darwin) PLATFORM="macos" ;;
  Linux)  PLATFORM="linux" ;;
  *)      error "Unsupported OS: $(uname -s)" ;;
esac

info "Installing DockPilot on $PLATFORM…"

# ── Python check ──────────────────────────────────────────────────────────────
PYTHON=""
for py in python3.13 python3.12 python3.11 python3.10 python3; do
  if command -v "$py" &>/dev/null; then
    ver="$("$py" -c 'import sys; print(sys.version_info[:2])')"
    if "$py" -c 'import sys; sys.exit(0 if sys.version_info >= (3,10) else 1)' 2>/dev/null; then
      PYTHON="$py"
      break
    fi
  fi
done
[[ -z "$PYTHON" ]] && error "Python 3.10+ is required. Install it and re-run."
info "Using $(${PYTHON} --version)"

# ── Git check ─────────────────────────────────────────────────────────────────
command -v git &>/dev/null || error "git is required. Install it and re-run."

# ── Clone or update ───────────────────────────────────────────────────────────
if [[ -d "$INSTALL_DIR/.git" ]]; then
  info "Updating existing installation…"
  git -C "$INSTALL_DIR" pull --ff-only
else
  info "Cloning DockPilot to $INSTALL_DIR…"
  git clone --depth=1 "$REPO_URL" "$INSTALL_DIR"
fi

# ── Python virtual environment ────────────────────────────────────────────────
VENV="$INSTALL_DIR/.venv"
if [[ ! -d "$VENV" ]]; then
  info "Creating virtual environment…"
  "$PYTHON" -m venv "$VENV"
fi

info "Installing Python dependencies…"
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"

# ── Shell launcher ────────────────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/usr/bin/env bash
# DockPilot launcher — auto-generated by install.sh
exec "$VENV/bin/python" "$INSTALL_DIR/main.py" "\$@"
LAUNCHER_EOF
chmod +x "$LAUNCHER"
info "Launcher created: $LAUNCHER"

# ── Linux: .desktop file ──────────────────────────────────────────────────────
if [[ "$PLATFORM" == "linux" ]]; then
  mkdir -p "$(dirname "$DESKTOP_FILE")"

  # Resolve icon path (fall back to a generic name if PNG not present)
  if [[ -f "$ICON_SRC" ]]; then
    ICON_VALUE="$ICON_SRC"
  else
    ICON_VALUE="utilities-terminal"
  fi

  cat > "$DESKTOP_FILE" << DESKTOP_EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=DockPilot
Comment=Lightweight Docker Desktop replacement
Exec=$LAUNCHER %u
Icon=$ICON_VALUE
Terminal=false
Categories=System;
Keywords=docker;container;
DESKTOP_EOF

  # Refresh app menu if possible
  command -v update-desktop-database &>/dev/null && \
    update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true

  info ".desktop file created: $DESKTOP_FILE"
fi

# ── macOS: PATH hint ──────────────────────────────────────────────────────────
if [[ "$PLATFORM" == "macos" ]]; then
  if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    warn "$BIN_DIR is not in your PATH."
    warn "Add the following line to your ~/.zshrc (or ~/.bashrc):"
    warn "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  fi
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
info "DockPilot installed successfully!"
info "Run it with:  dockpilot"
if [[ "$PLATFORM" == "macos" ]]; then
  info "(Restart your terminal if 'dockpilot' is not found yet)"
fi
